### ISSUE TITLE
Memo: working repository

### ISSUE THREAD

**Issue by junaruga** [modularity-modules/autotools#1]
I am working in this repository to create `modulemd.yaml`.
https://github.com/junaruga/modules-autotools

**Comment by alexxa** [comment]
@junaruga is it still valid? Close it, probably? autotools installs fine in the latest boltron-f27 image.

**Comment by junaruga** [comment]
No, it is not valid.
Thanks for the reporting me.
A kind person prepared modules/autotools instead of me.
I would close this ticket.

**Comment by junaruga** [comment]
@alexxa where is the latest boltron-f27 image?

It is still not in https://hub.docker.com/_/fedora/

This one?
https://github.com/container-images/boltron-27

**Comment by whitel** [comment]
@junaruga correct, however, some of the mirrors are not updated, so watch the sources.

**Comment by junaruga** [comment]
@whitel ok! thanks for the information.
